/*------------------------------------------------------------------------
    File        : ${relativeFile#find=^.*src\/#replace=#}
    Purpose     : ${cursor}
    Author(s)   : ${author}
    Created     : ${dateTimeFormat}    
  ----------------------------------------------------------------------*/

interface ${relativeFile#find=^.*src\/#replace=##find=/#flags=g#replace=.##find=\.cls$#replace=#}:


end interface.